name: Bandit push test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install bandit
      - run : |
          bandit -r . --severity-level high
